/**
 * send-report.js
 * Writes a daily pipeline summary to GitHub Actions Job Summary.
 * Visible directly in the Actions tab — no email service needed.
 *
 * Usage: node scripts/send-report.js
 */

import fs from 'fs';
import path from 'path';

const GITHUB_STEP_SUMMARY = process.env.GITHUB_STEP_SUMMARY;

// Collect logs from today's run
function collectLogs() {
  const logsDir = path.resolve('logs');
  const today = new Date().toISOString().slice(0, 10);
  const summary = {
    date: today,
    agents: [],
    errors: [],
  };

  if (!fs.existsSync(logsDir)) {
    summary.errors.push('No logs directory found');
    return summary;
  }

  const files = fs.readdirSync(logsDir).filter((f) => f.includes(today));

  for (const file of files) {
    const content = fs.readFileSync(path.join(logsDir, file), 'utf-8');
    const agent = file.split('-')[0];

    try {
      const data = JSON.parse(content);
      summary.agents.push({
        name: agent,
        status: data.status || 'completed',
        itemsProcessed: data.itemsProcessed || 0,
        errors: data.errors || [],
        duration: data.duration || '—',
      });
    } catch {
      summary.agents.push({
        name: agent,
        status: content.includes('ERROR') ? 'error' : 'completed',
        itemsProcessed: '—',
        duration: '—',
      });
    }
  }

  return summary;
}

// Format as markdown for GitHub Job Summary
function formatMarkdown(summary) {
  const statusIcon = (s) => (s === 'completed' ? '✅' : '❌');

  const agentRows = summary.agents
    .map((a) => `| ${statusIcon(a.status)} ${a.name} | ${a.status} | ${a.itemsProcessed} | ${a.duration} |`)
    .join('\n');

  return `# 🐱 MealMeow Daily Pipeline Report
**${summary.date}**

## Agent Results

| Agent | Status | Items Processed | Duration |
|-------|--------|-----------------|----------|
${agentRows || '| — | No agents ran | — | — |'}

${
  summary.errors.length > 0
    ? `## ⚠️ Errors\n${summary.errors.map((e) => `- ${e}`).join('\n')}`
    : '## ✅ No errors'
}

---
*Generated by MealMeow Agent Pipeline*
`;
}

// Main
const summary = collectLogs();
const md = formatMarkdown(summary);

// Write to GitHub Actions Job Summary
if (GITHUB_STEP_SUMMARY) {
  fs.appendFileSync(GITHUB_STEP_SUMMARY, md);
  console.log('Report written to GitHub Actions Job Summary');
} else {
  // Local run — print to stdout
  console.log(md);
}

// Also save to logs
const reportPath = path.resolve('logs', `report-${summary.date}.md`);
fs.writeFileSync(reportPath, md);
console.log(`Report saved to ${reportPath}`);
